name: Build-and-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        cargo-cmd: [build, test]
        feature-flag: [--no-default-features, --all-features]
        mode-flag: [null, --release]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - run: cargo ${{ matrix.cargo-cmd }} ${{ matrix.feature-flag }} ${{ matrix.mode-flag }} --verbose
